server:
  port: 8082

spring:
  application:
    name: SpringBootProject1Demo

#logging:
#  level:
#    root: INFO
#    com.example: TRACE
#  file:
#    name: application.log
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"

